cmake: install missing header `impl/zerocopy_io.h` (#4328)
Summary:
Not installing this header would make `tests/test_zerocopy.cpp` fail to compile outside the project source tree.

```
[1/35] /usr/bin/c++  -I/tmp/autopkgtest.v36ELd/autopkgtest_tmp/tests/../include -O3 -DNDEBUG -fopenmp -DGTEST_HAS_PTHREAD=1 -MD -MT CMakeFiles/faiss_test.dir/test_zerocopy.cpp.o -MF CMakeFiles/faiss_test.dir/test_zerocopy.cpp.o.d -o CMakeFiles/faiss_test.dir/test_zerocopy.cpp.o -c /tmp/autopkgtest.v36ELd/autopkgtest_tmp/tests/test_zerocopy.cpp
FAILED: CMakeFiles/faiss_test.dir/test_zerocopy.cpp.o
/usr/bin/c++  -I/tmp/autopkgtest.v36ELd/autopkgtest_tmp/tests/../include -O3 -DNDEBUG -fopenmp -DGTEST_HAS_PTHREAD=1 -MD -MT CMakeFiles/faiss_test.dir/test_zerocopy.cpp.o -MF CMakeFiles/faiss_test.dir/test_zerocopy.cpp.o.d -o CMakeFiles/faiss_test.dir/test_zerocopy.cpp.o -c /tmp/autopkgtest.v36ELd/autopkgtest_tmp/tests/test_zerocopy.cpp
/tmp/autopkgtest.v36ELd/autopkgtest_tmp/tests/test_zerocopy.cpp:18:10: fatal error: faiss/impl/zerocopy_io.h: No such file or directory
   18 | #include <faiss/impl/zerocopy_io.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Pull Request resolved: https://github.com/facebookresearch/faiss/pull/4328

Reviewed By: satymish

Differential Revision: D74293366

Pulled By: junjieqi

fbshipit-source-id: d4f9b5eb640e261588191fc8c62ae40a354d4c4d