Update INSTALL.md to remove some raft references, add missing dependency (#4176)
Summary:
Pull Request resolved: https://github.com/facebookresearch/faiss/pull/4176

For issue: https://github.com/facebookresearch/faiss/issues/4175

Reproduce on CI by:

1. Update build-pull-request.yml and action.yml to only run `conda install -c pytorch -c nvidia -c rapidsai -c conda-forge faiss-gpu-cuvs`, and also start a tmate session.

2. Log into the host

3. `cd` to ~/miniconda3/bin. Try to import faiss. It fails

```
runner@fv-az802-878:~/miniconda3/bin$ ./python
Python 3.12.8 | packaged by conda-forge | (main, Dec  5 2024, 14:24:40) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import faiss
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/runner/miniconda3/lib/python3.12/site-packages/faiss/__init__.py", line 17, in <module>
    from .loader import *
  File "/home/runner/miniconda3/lib/python3.12/site-packages/faiss/loader.py", line 149, in <module>
    from .swigfaiss import *
  File "/home/runner/miniconda3/lib/python3.12/site-packages/faiss/swigfaiss.py", line 13, in <module>
    from . import _swigfaiss
ImportError: libnvJitLink.so.12: cannot open shared object file: No such file or directory
>>>
```

Reviewed By: asadoughi

Differential Revision: D69278685

fbshipit-source-id: 44c476c9ab3de5a43edb6da45cbb32a80df90160