Add missing Thrust includes (#4597)
Summary:
While testing cuVS with a prerelease build of CCCL 3.1.x, I encountered compilation errors. There were some missing Thrust headers needed for `thrust::copy` and `thrust::device_ptr`.

This is being patched in cuVS as a workaround for now: https://github.com/rapidsai/cuvs/pull/1398

This PR upstreams the patch.

Errors look like this:

```
FAILED: [code=2] _deps/faiss-build/faiss/gpu/CMakeFiles/faiss_gpu_objs.dir/impl/BinaryCuvsCagra.cu.o
sccache $BUILD_PREFIX/bin/nvcc -forward-unknown-to-host-compiler -DCCCL_DISABLE_PDL -DCUB_DISABLE_NAMESPACE_MAGIC -DCUB_IGNORE_NAMESPACE_MAGIC_ERROR -DCUTLASS_NAMESPACE=raft_cutlass -DCUVS_BUILD_CAGRA_HNSWLIB -DLIBCUDACXX_ENABLE_EXPERIMENTAL_MEMORY_RESOURCE -DRAFT_LOG_ACTIVE_LEVEL=RAPIDS_LOGGER_LOG_LEVEL_INFO -DRAFT_SYSTEM_LITTLE_ENDIAN=1 -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CUDA -DTHRUST_DISABLE_ABI_NAMESPACE -DTHRUST_HOST_SYSTEM=THRUST_HOST_SYSTEM_CPP -DTHRUST_IGNORE_ABI_NAMESPACE_ERROR -DUSE_NVIDIA_CUVS=1 -I$SRC_DIR/cpp/build/_deps/faiss-src -I$SRC_DIR/cpp/include -I$SRC_DIR/cpp/build/_deps/cccl-src/lib/cmake/thrust/../../../thrust -I$SRC_DIR/cpp/build/_deps/cccl-src/lib/cmake/libcudacxx/../../../libcudacxx/include -I$SRC_DIR/cpp/build/_deps/cccl-src/lib/cmake/cub/../../../cub -I$SRC_DIR/cpp/build/_deps/hnswlib-src -isystem $BUILD_PREFIX/targets/x86_64-linux/include -isystem $BUILD_PREFIX/targets/x86_64-linux/include/cccl -isystem $PREFIX/targets/x86_64-linux/include -isystem $PREFIX/include -isystem $BUILD_PREFIX/include -O3 -DNDEBUG "--generate-code=arch=compute_75,code=[sm_75]" "--generate-code=arch=compute_80,code=[sm_80]" "--generate-code=arch=compute_86,code=[sm_86]" "--generate-code=arch=compute_90a,code=[sm_90a]" "--generate-code=arch=compute_100f,code=[sm_100f]" "--generate-code=arch=compute_120a,code=[sm_120a]" "--generate-code=arch=compute_120,code=[compute_120,sm_120]" -Xcompiler=-fPIC -Xfatbin=-compress-all --expt-extended-lambda --expt-relaxed-constexpr -Xcompiler=-fopenmp -Xcompiler -pthread "-Xcompiler=-ffile-prefix-map=$PREFIX/=''" -MD -MT _deps/faiss-build/faiss/gpu/CMakeFiles/faiss_gpu_objs.dir/impl/BinaryCuvsCagra.cu.o -MF _deps/faiss-build/faiss/gpu/CMakeFiles/faiss_gpu_objs.dir/impl/BinaryCuvsCagra.cu.o.d -x cu -c $SRC_DIR/cpp/build/_deps/faiss-src/faiss/gpu/impl/BinaryCuvsCagra.cu -o _deps/faiss-build/faiss/gpu/CMakeFiles/faiss_gpu_objs.dir/impl/BinaryCuvsCagra.cu.o
$SRC_DIR/cpp/build/_deps/faiss-src/faiss/gpu/impl/BinaryCuvsCagra.cu(102): error: namespace "thrust" has no member "copy"
          thrust::copy(
                  ^
$SRC_DIR/cpp/build/_deps/faiss-src/faiss/gpu/impl/BinaryCuvsCagra.cu(258): error: namespace "thrust" has no member "copy"
      thrust::copy(
              ^
$SRC_DIR/cpp/build/_deps/faiss-src/faiss/gpu/impl/BinaryCuvsCagra.cu(300): error: namespace "thrust" has no member "copy"
      thrust::copy(
              ^
3 errors detected in the compilation of "$SRC_DIR/cpp/build/_deps/faiss-src/faiss/gpu/impl/BinaryCuvsCagra.cu".
```

```
FAILED: [code=2] _deps/faiss-build/faiss/gpu/CMakeFiles/faiss_gpu_objs.dir/impl/CuvsCagra.cu.o
sccache $BUILD_PREFIX/bin/nvcc -forward-unknown-to-host-compiler -DCCCL_DISABLE_PDL -DCUB_DISABLE_NAMESPACE_MAGIC -DCUB_IGNORE_NAMESPACE_MAGIC_ERROR -DCUTLASS_NAMESPACE=raft_cutlass -DCUVS_BUILD_CAGRA_HNSWLIB -DLIBCUDACXX_ENABLE_EXPERIMENTAL_MEMORY_RESOURCE -DRAFT_LOG_ACTIVE_LEVEL=RAPIDS_LOGGER_LOG_LEVEL_INFO -DRAFT_SYSTEM_LITTLE_ENDIAN=1 -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CUDA -DTHRUST_DISABLE_ABI_NAMESPACE -DTHRUST_HOST_SYSTEM=THRUST_HOST_SYSTEM_CPP -DTHRUST_IGNORE_ABI_NAMESPACE_ERROR -DUSE_NVIDIA_CUVS=1 -I$SRC_DIR/cpp/build/_deps/faiss-src -I$SRC_DIR/cpp/include -I$SRC_DIR/cpp/build/_deps/cccl-src/lib/cmake/thrust/../../../thrust -I$SRC_DIR/cpp/build/_deps/cccl-src/lib/cmake/libcudacxx/../../../libcudacxx/include -I$SRC_DIR/cpp/build/_deps/cccl-src/lib/cmake/cub/../../../cub -I$SRC_DIR/cpp/build/_deps/hnswlib-src -isystem $BUILD_PREFIX/targets/x86_64-linux/include -isystem $BUILD_PREFIX/targets/x86_64-linux/include/cccl -isystem $PREFIX/targets/x86_64-linux/include -isystem $PREFIX/include -isystem $BUILD_PREFIX/include -O3 -DNDEBUG "--generate-code=arch=compute_75,code=[sm_75]" "--generate-code=arch=compute_80,code=[sm_80]" "--generate-code=arch=compute_86,code=[sm_86]" "--generate-code=arch=compute_90a,code=[sm_90a]" "--generate-code=arch=compute_100f,code=[sm_100f]" "--generate-code=arch=compute_120a,code=[sm_120a]" "--generate-code=arch=compute_120,code=[compute_120,sm_120]" -Xcompiler=-fPIC -Xfatbin=-compress-all --expt-extended-lambda --expt-relaxed-constexpr -Xcompiler=-fopenmp -Xcompiler -pthread "-Xcompiler=-ffile-prefix-map=$PREFIX/=''" -MD -MT _deps/faiss-build/faiss/gpu/CMakeFiles/faiss_gpu_objs.dir/impl/CuvsCagra.cu.o -MF _deps/faiss-build/faiss/gpu/CMakeFiles/faiss_gpu_objs.dir/impl/CuvsCagra.cu.o.d -x cu -c $SRC_DIR/cpp/build/_deps/faiss-src/faiss/gpu/impl/CuvsCagra.cu -o _deps/faiss-build/faiss/gpu/CMakeFiles/faiss_gpu_objs.dir/impl/CuvsCagra.cu.o
$SRC_DIR/cpp/build/_deps/faiss-src/faiss/gpu/impl/CuvsCagra.cu(126): error: namespace "thrust" has no member "copy"
          thrust::copy(
                  ^
$SRC_DIR/cpp/build/_deps/faiss-src/faiss/gpu/impl/CuvsCagra.cu(292): error: namespace "thrust" has no member "copy"
      thrust::copy(
              ^
$SRC_DIR/cpp/build/_deps/faiss-src/faiss/gpu/impl/CuvsCagra.cu(324): error: namespace "thrust" has no member "copy"
      thrust::copy(
              ^
3 errors detected in the compilation of "$SRC_DIR/cpp/build/_deps/faiss-src/faiss/gpu/impl/CuvsCagra.cu".
```

Pull Request resolved: https://github.com/facebookresearch/faiss/pull/4597

Reviewed By: junjieqi

Differential Revision: D83686425

Pulled By: mnorris11

fbshipit-source-id: 8adf8dacc64b582483ca78cb00ff5d380d616704