Remove unused variable
Summary:
We have a toolchain which some builds seems to have included this dependency recently. For some reason it's causing failures, notably because of this unused variable:

```counterexample,name=failed build
[kevinhui@devvm27613.ftw0 ~/fbsource/fbcode (23b15f2f1a|remote/master)]$ buck2 bxl "fbcode//mode/opt" ...
Action failed: fbcode//faiss:faiss (cxx_compile index_factory.cpp (pic))
Remote command returned non-zero exit code 1
Reproduce locally: `frecli cas download-action 0bda7fa291272164aa05567adae07bc25e3c41e7ea4a573f14413540b63587d4:145`
stdout:
stderr:
fbcode/faiss/index_factory.cpp:196:19: error: unused variable 'rabitq_pattern' [-Werror,-Wunused-const-variable]
  196 | const std::string rabitq_pattern = "(RaBitQ)";
      |                   ^~~~~~~~~~~~~~
1 error generated.
Error: command failed
create_dir_all(/data/sandcastle/temp/skycastle)

Caused by:
    Permission denied (os error 13)
Buck UI: https://www.internalfb.com/buck2/28ccbaf8-d0be-498d-b671-1bd85a60423e
Network: Up: 3.2MiB  Down: 871MiB  (reSessionID-c1db63d9-5133-4daf-aff5-e4313796c6e6)
Loading targets.   Remaining      0/46764                                                              129632 dirs read, 1112926 targets declared
Analyzing targets. Remaining      0/183358                                                             944809 actions, 1075889 artifacts declared
Executing actions. Remaining      0/196171                                                             2:34:19.2s exec time total
Command: bxl.      Finished 275 local, 1543 remote, 4568 cache (72% hit)                               1:24:19.9s exec time cached (54%)
Time elapsed: 1:59.5s
BXL FAILED
[kevinhui@devvm27613.ftw0 ~/fbsource/fbcode (23b15f2f1a|remote/master)]$
```

A quick `fbgs` shows that this is the only variable in your directory: https://fburl.com/code/uoh6rnu3, so hopefully should be fine to build.

Reviewed By: henrywang8atfbdotcom

Differential Revision: D87786317

fbshipit-source-id: 13e85722831bc1d76d82e0224f1d5ce640880252