AIX compilation fix for io classes (#3275)
Summary:
in AIX OS ,as fileno is defined as C macro,   we get the compilation error during preprocessing step.

In file included from /ranjit/Faiss/faiss/faiss/invlists/InvertedListsIOHook.h:10:
/ranjit/Faiss/faiss/faiss/impl/io.h:35:17: error: expected member name or ';' after declaration specifiers
   35 |     virtual int fileno();
      |     ~~~~~~~~~~~ ^
/usr/include/stdio.h:517:30: note: expanded from macro 'fileno'
  517 | #define fileno(__p)     ((__p)->_file)

Pull Request resolved: https://github.com/facebookresearch/faiss/pull/3275

Reviewed By: algoriddle

Differential Revision: D54944388

Pulled By: mdouze

fbshipit-source-id: 40c4314de93547778ac274281245ff59e3a18b6d