Add missing #include in code_distance-sve.h (#4219)
Summary:
Pull Request resolved: https://github.com/facebookresearch/faiss/pull/4219

`code_distance-sve.h` references `PQDecoder8` but doesn't include the header. The issue is revealed by D68784260 which removed some includes from a header that indirectly included `ProductQuantizer.h`

```
headers/faiss/impl/code_distance/code_distance-sve.h:74:45: error: unknown type name 'PQDecoder8'; did you mean 'PQDecoderT'?
       74 | std::enable_if_t<std::is_same_v<PQDecoderT, PQDecoder8>, float> inline distance_single_code_sve(
          |                                             ^~~~~~~~~~
          |                                             PQDecoderT
```

Reviewed By: ddrcoder

Differential Revision: D70433576

fbshipit-source-id: 12945b16003a3d6a995b18ffe9798179ecf826f4